CC = gcc
CFLAGS = -Wall

all: TimeSysCall TimeSignal

TimeSysCall: TimeSysCall.c
	$(CC) $(CFLAGS) TimeSysCall.c -o TimeSysCall

TimeSignal: TimeSignal.c
	$(CC) $(CFLAGS) TimeSignal.c -o TimeSignal

clean:
	rm -f TimeSysCall TimeSignal
